#!/usr/bin/env bash
set -e

SIF="/w/halld-scshelf2101/lng/WORK/PyAmpTools9/pyamptools.sif"
BIND="/volatile/halld/home/dbarton,/cache/halld/home/dbarton,/work/halld/home/dbarton/gluex,/scratch"
WORKDIR="/work/halld/home/dbarton/gluex/KShortPipLambda/eventSelection"
PDF="$WORKDIR/plots/plots.pdf"
LOG="$WORKDIR/runplotsOUT.txt"

echo "Starting runplots at $(date)" > "$LOG"

nohup apptainer exec --contain --writable-tmpfs -B "$BIND" --env BASH_ENV=/dev/null "$SIF" \
  bash -lc "cd '$WORKDIR'; source /etc/bash.bashrc; python3 plots.py; sync; sleep 0.1" \
  >> "$LOG" 2>&1 &

PID=$!
echo "runplots started in background. Log: $LOG"
echo "PID: $PID"


exit 0