/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROO2BW
#define ROO2BW

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class Roo2BW : public RooAbsPdf {
public:
  Roo2BW() {} ; 
  Roo2BW(const char *name, const char *title,
	    RooAbsReal& _x,
 	    RooAbsReal& _mass1,
	    RooAbsReal& _width1,
	    RooAbsReal& _spin1,
	    RooAbsReal& _mass2,
	    RooAbsReal& _width2,
	    RooAbsReal& _spin2,
	    RooAbsReal& _scale,
	    RooAbsReal& _Phi,
	    RooAbsReal& _rInt, 
	    RooAbsReal& _massA,
	    RooAbsReal& _massB);
  Roo2BW(const Roo2BW& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new Roo2BW(*this,newname); }
  inline virtual ~Roo2BW() { }

protected:

  RooRealProxy x ;
  RooRealProxy mass1 ;
  RooRealProxy width1 ;
  RooRealProxy spin1 ;
  RooRealProxy mass2 ;
  RooRealProxy width2 ;
  RooRealProxy spin2 ;
  RooRealProxy scale ;
  RooRealProxy Phi ;
  RooRealProxy rInt ; //relative interference
  RooRealProxy massA ;
  RooRealProxy massB ;
  
  Double_t evaluate() const ;

private:

  Double_t breakupMomentum(double mass0, double mass1, double mass2) const;
  Double_t barrierFactor( double q, int spinP ) const;

  ClassDef(Roo2BW,1) // Your description goes here...
};
 
#endif
