/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROO2BW1S_H
#define ROO2BW1S_H

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class Roo2BW1S : public RooAbsPdf {
public:
  Roo2BW1S() {} ; 
  Roo2BW1S(const char *name, const char *title,
	    RooAbsReal& _x,
 	    RooAbsReal& _mass1,
	    RooAbsReal& _width1,
	    RooAbsReal& _spin1,
	    RooAbsReal& _mass2,
	    RooAbsReal& _width2,
	    RooAbsReal& _spin2,
	    RooAbsReal& _scale,
	    RooAbsReal& _Phi,
	    RooAbsReal& _aScat,
	    RooAbsReal& _rEff,
	    RooAbsReal& _scaleS,
	    RooAbsReal& _phaseS,
	    RooAbsReal& _massA,
	    RooAbsReal& _massB);
  Roo2BW1S(const Roo2BW1S& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new Roo2BW1S(*this,newname); }
  inline virtual ~Roo2BW1S() { }

protected:

  RooRealProxy x ;
  RooRealProxy mass1 ;
  RooRealProxy width1 ;
  RooRealProxy spin1 ;
  RooRealProxy mass2 ;
  RooRealProxy width2 ;
  RooRealProxy spin2 ;
  RooRealProxy scale ;
  RooRealProxy Phi ;
  RooRealProxy aScat ;   // LASS scattering length
  RooRealProxy rEff ;    // LASS effective range
  RooRealProxy scaleS ;  // S-wave magnitude
  RooRealProxy phaseS ;  // S-wave phase
  RooRealProxy massA ;
  RooRealProxy massB ;
  
  Double_t evaluate() const ;

private:

  Double_t breakupMomentum(double mass0, double mass1, double mass2) const;
  Double_t barrierFactor( double q, int spinP ) const;

  ClassDef(Roo2BW1S,1) // Your description goes here...
};
 
#endif
