#!/usr/bin/env bash
set -e

SIF="/w/halld-scshelf2101/lng/WORK/PyAmpTools9/pyamptools.sif"
BIND="/volatile/halld/home/dbarton,/cache/halld/home/dbarton,/work/halld/home/dbarton/gluex,/scratch"
WORKDIR="/work/halld/home/dbarton/gluex/KShortPipLambda/sdme"
PDF="$WORKDIR/plots/sdme_plots.pdf"

apptainer exec --contain --writable-tmpfs -B "$BIND" --env BASH_ENV=/dev/null "$SIF" \
  bash -lc "cd '$WORKDIR'; source /etc/bash.bashrc; python3 plots_sdme.py; sync; sleep 0.1"

# Open the PDF on the host, fully detached
( command -v xdg-open >/dev/null && nohup xdg-open "$PDF" >/dev/null 2>&1 ) \
 || ( command -v gio >/dev/null && nohup gio open "$PDF" >/dev/null 2>&1 ) \
 || nohup evince "$PDF" >/dev/null 2>&1 &


exit 0