/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOT1BW
#define ROOT1BW

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class Roo1BW : public RooAbsPdf {
public:
  Roo1BW() {} ; 
  Roo1BW(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mass,
	      RooAbsReal& _width,
	      RooAbsReal& _spin,
	      RooAbsReal& _massA,
	      RooAbsReal& _massB);
  Roo1BW(const Roo1BW& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new Roo1BW(*this,newname); }
  inline virtual ~Roo1BW() { }

protected:

  RooRealProxy x ;
  RooRealProxy mass ;
  RooRealProxy width ;
  RooRealProxy spin ;
  RooRealProxy massA ;
  RooRealProxy massB ;
  
  Double_t evaluate() const ;

private:

  Double_t breakupMomentum(double mass0, double mass1, double mass2) const;
  Double_t barrierFactor( double q, int spinP ) const;

  ClassDef(Roo1BW,1) // Your description goes here...
};
 
#endif
