/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooTestBW.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 
#include "complex.h"

ClassImp(RooTestBW); 

 RooTestBW::RooTestBW(const char *name, const char *title, 
                        RooAbsReal& _x,
                        RooAbsReal& _mass,
                        RooAbsReal& _width,
                        RooAbsReal& _spin,
                        RooAbsReal& _massA,
                        RooAbsReal& _massB) :
   RooAbsPdf(name,title), 
   x("x","x",this,_x),
   mass("mass","mass",this,_mass),
   width("width","width",this,_width),
   spin("spin","spin",this,_spin),
   massA("massA","massA",this,_massA),
   massB("massB","massB",this,_massB)
 { 
 } 


 RooTestBW::RooTestBW(const RooTestBW& other, const char* name) :  
   RooAbsPdf(other,name), 
   x("x",this,other.x),
   mass("mass",this,other.mass),
   width("width",this,other.width),
   spin("spin",this,other.spin),
   massA("massA",this,other.massA),
   massB("massB",this,other.massB)
 { 
 } 



 Double_t RooTestBW::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 

  // assert positive breakup momenta     
  Double_t q0 = fabs( breakupMomentum(mass, massA, massB) );
  Double_t q  = fabs( breakupMomentum(x,    massA, massB) );
  
  Double_t F0 = barrierFactor(q0, spin);
  Double_t F  = barrierFactor(q,  spin);
  
  Double_t calc_width = width*(mass/x)*(q/q0)*((F*F)/(F0*F0));

  
  // this first factor just gets normalization right for BW's that have
  // no additional s-dependence from orbital L
  // complex<Double_t> bwtop( sqrt( mass * width / TMath::Pi() ), 0.0 );
  complex<Double_t> bwtop( sqrt( x * calc_width / TMath::Pi() ), 0.0 );
  complex<Double_t> bwbottom( ( mass*mass - x*x ) ,
                           -1.0 * ( mass * calc_width ) );
  
  return( norm( F * bwtop / bwbottom ) );
 
 } 


Double_t RooTestBW::breakupMomentum(double mass0, double mass1, double mass2) const
{
  double q;
  //mass 1 and mass 2 are the daughters of mass 0
	// fabs -- correct?  consistent w/ previous E852 code
        q = sqrt( fabs(   mass0*mass0*mass0*mass0 + 
			  mass1*mass1*mass1*mass1 +
			  mass2*mass2*mass2*mass2 -
			  2.0*mass0*mass0*mass1*mass1 -
			  2.0*mass0*mass0*mass2*mass2 -
			  2.0*mass1*mass1*mass2*mass2  ) ) / (2.0 * mass0);

        return q;
	
}

Double_t RooTestBW::barrierFactor( double q, int spinP ) const
{  

  double barrier = 1;
  double z;

  z = ( (q*q) / (0.1973*0.1973) );

  switch (spinP){

  case 0:
    barrier = 1.0;
    break;

  case 1:
    barrier = sqrt( (2.0*z) /
		    (z + 1.0) );
    break;
        
  case 2:
    barrier = sqrt( (13.0*z*z) /
		    ((z-3.0)*(z-3.0) + 9.0*z) );
    break;
  }

  return barrier;

}
