/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOTESTBW
#define ROOTESTBW

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooTestBW : public RooAbsPdf {
public:
  RooTestBW() {} ; 
  RooTestBW(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mass,
	      RooAbsReal& _width,
	      RooAbsReal& _spin,
	      RooAbsReal& _massA,
	      RooAbsReal& _massB);
  RooTestBW(const RooTestBW& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooTestBW(*this,newname); }
  inline virtual ~RooTestBW() { }

protected:

  RooRealProxy x ;
  RooRealProxy mass ;
  RooRealProxy width ;
  RooRealProxy spin ;
  RooRealProxy massA ;
  RooRealProxy massB ;
  
  Double_t evaluate() const ;

private:

  Double_t breakupMomentum(double mass0, double mass1, double mass2) const;
  Double_t barrierFactor( double q, int spinP ) const;

  ClassDef(RooTestBW,1) // Your description goes here...
};
 
#endif
